### ISSUE TITLE
Why ArrayList for Reponse's headers ?

### ISSUE THREAD

**Issue by Julien00859** [Julien00859/JWS#1]
Is there a reason to use an ArrayList over a Set in the Response class for the headers ? Or can we use a Set to prevent Header duplication ?

**Comment by izanagi1995** [comment]
I use ArrayList for usage easiness, you can use a Set. But as said in
RFC2616, headers are never duplicated.

Le 23 nov. 2016 20:56, "Julien Castiaux" notifications@github.com a
écrit :

**Comment by Julien00859** [comment]
Or even an hashmap ? header label as key, header value as value ? I'll go for that

**Comment by izanagi1995** [comment]
Hashmap iteration is an heavy shit

Le 23 nov. 2016 21:14, "Julien Castiaux" notifications@github.com a
écrit :
